name: Fload

on:
  issues:
    types: [opened]
  push:
    paths:
      - 'tre1.json'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Checkout Código
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: FloadTre
        run: |
          mvn compile
          mvn exec:java -Dexec.mainClass="com.project.ewall.ai" -Dexec.args="${{ github.event.issue.title }}"

      - name: Postar Resposta na Issue
        if: github.event_name == 'issues'
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          body: ""

      - name: Upload FloadTre
        uses: actions/upload-artifact@v3
        with:
          name: model
          path: output/model.ser
